#!/usr/bin/python3

#sum of all even numbers in a matrix

a = [[2, 3, 5],
     [4, 1, 9],
     [3, 1, 10]]
evenSum=0
for i in a:
  for j in i:
    if j%2==0:
      evenSum+=j
print(evenSum)
print("----------")

#transposing the matrix
def matrixTranspose(a):
    if not a: return []
    return [[row[i] for row in a] for i in range(len(a[0]))]
print(matrixTranspose(a))
