#!/usr/bin/python3


strParam = "hithamereddy"
n = len(strParam)
#if (n<4 or n>25):
#   print("the number of characters in your username should be between 4 and 25.")
#else:
#   print("valid username")
valid = "true"
for i in strParam:
    if i.isalpha() or i.isdigit() or i == "_":
        continue
    else:
        valid = "false"
        break
if (valid == "true"):
    if (n<4 or n>25):
        valid = "false"
    elif not strParam[0].isalpha():
        valid = "false"
    elif strParam[n-1] == "_":
        valid = "false"

print(valid)
